In [1]:
import pandas as pd
import re

In [2]:
df = pd.read_csv("../data/processed/multilingual_sentiment.csv")

df.head()

                                                text sentiment language
0  Next date - Birmingham, The Rainbow, Sun 7th J...  Positive  English
1   Action king dialogue semma..... avanoda sindh...  Positive    Tamil
2   Appedilaam nadekaathu, nadake kudaathu!! The ...  Positive    Tamil
3   Looks like d Mixture of  Kaala+Kabali.....   ...  Positive    Tamil
4                      Nfg greatest hits cd cracked   Negative  English

In [3]:
print(df.shape)

(30978, 3)

In [4]:
df["cleaned_text"] = df["text"]

In [5]:
df["cleaned_text"] = df["cleaned_text"].apply(
    lambda x: re.sub(r"http\S+|www\S+", "", str(x))
)

In [6]:
df[["text","cleaned_text"]].head()

,text,cleaned_text
0,"Next date - Birmingham, The Rainbow, Sun 7th J...","Next date - Birmingham, The Rainbow, Sun 7th J..."
1,Action king dialogue semma..... avanoda sindh...,Action king dialogue semma..... avanoda sindh...
2,"Appedilaam nadekaathu, nadake kudaathu!! The ...","Appedilaam nadekaathu, nadake kudaathu!! The ..."
3,Looks like d Mixture of Kaala+Kabali..... ...,Looks like d Mixture of Kaala+Kabali..... ...
4,Nfg greatest hits cd cracked,Nfg greatest hits cd cracked

In [7]:
df[["text","cleaned_text"]].head()

,text,cleaned_text
0,"Next date - Birmingham, The Rainbow, Sun 7th J...","Next date - Birmingham, The Rainbow, Sun 7th J..."
1,Action king dialogue semma..... avanoda sindh...,Action king dialogue semma..... avanoda sindh...
2,"Appedilaam nadekaathu, nadake kudaathu!! The ...","Appedilaam nadekaathu, nadake kudaathu!! The ..."
3,Looks like d Mixture of Kaala+Kabali..... ...,Looks like d Mixture of Kaala+Kabali..... ...
4,Nfg greatest hits cd cracked,Nfg greatest hits cd cracked

In [8]:
df["cleaned_text"] = df["cleaned_text"].str.replace(
    "#",
    "",
    regex=False
)

In [9]:
df["cleaned_text"] = df["cleaned_text"].apply(
    lambda x: re.sub(r"\d+", "", str(x))
)

In [10]:
df["cleaned_text"] = df["cleaned_text"].apply(
    lambda x: re.sub(
        r"[^\w\s\u0B80-\u0BFF\u0900-\u097F]",
        "",
        str(x)
    )
)

In [11]:
df["cleaned_text"] = df["cleaned_text"].str.lower()

In [12]:
df["cleaned_text"] = df["cleaned_text"].apply(
    lambda x: " ".join(x.split())
)

In [13]:
df = df[df["cleaned_text"].str.strip() != ""]

In [14]:
df[
    ["text","cleaned_text"]
].sample(10)

,text,cleaned_text
25780,hey taylor do you know of anywhere i can see t...,hey taylor do you know of anywhere i can see t...
14551,Comments pakka ethana per. Vandhurkinga hit l...,comments pakka ethana per vandhurkinga hit lik...
10887,I sold my car,i sold my car
5590,home...still hasnt set in that i wont be going...,homestill hasnt set in that i wont be going to...
25654,Ennada mersal teaser likes kooda varla but th...,ennada mersal teaser likes kooda varla but tha...
13032,All the best Ajith SIR - Pink was outstanding...,all the best ajith sir pink was outstanding so...
30640,Teaser ah vidama trailer ah vittutaga🤩🤩🤩🤩🤩,teaser ah vidama trailer ah vittutaga
25991,How lovely is the weather waiting for superna...,how lovely is the weather waiting for supernat...
4211,vera level trailerda bigilukku ippaye sanga u...,vera level trailerda bigilukku ippaye sanga ut...
20057,Sema sir inimel ipadi oru padam varadhu,sema sir inimel ipadi oru padam varadhu

In [15]:
df.to_csv(
    "../data/processed/multilingual_sentiment_cleaned.csv",
    index=False
)

print("Saved successfully")

Saved successfully

In [16]:
print(df.shape)

df[["text", "cleaned_text"]].head(10)

(30978, 4)

,text,cleaned_text
0,"Next date - Birmingham, The Rainbow, Sun 7th J...",next date birmingham the rainbow sun th june s...
1,Action king dialogue semma..... avanoda sindh...,action king dialogue semma avanoda sindhanayum...
2,"Appedilaam nadekaathu, nadake kudaathu!! The ...",appedilaam nadekaathu nadake kudaathu the bull...
3,Looks like d Mixture of Kaala+Kabali..... ...,looks like d mixture of kaalakabali sure antho...
4,Nfg greatest hits cd cracked,nfg greatest hits cd cracked
5,Sry ppls listenin to good music in a good mood...,sry ppls listenin to good music in a good mood...
6,TWitter!!! Finally joined Follow me i'll foll...,twitter finally joined follow me ill follow u d
7,going to see UP in about an hour.,going to see up in about an hour
8,I love you SK Anna,i love you sk anna
9,69 vayasula avaroda stylea parrungada we love...,vayasula avaroda stylea parrungada we love u t...

In [17]:
print(df.shape)

(30978, 4)

Final cleaned dataset shape: (30878, 4)
Columns:
- text
- sentiment
- language
- cleaned_text