In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
df = pd.read_csv(
    "../data/processed/multilingual_sentiment_cleaned.csv"
)

df.head()

,text,sentiment,language,cleaned_text
0,"Next date - Birmingham, The Rainbow, Sun 7th J...",Positive,English,next date birmingham the rainbow sun th june s...
1,Action king dialogue semma..... avanoda sindh...,Positive,Tamil,action king dialogue semma avanoda sindhanayum...
2,"Appedilaam nadekaathu, nadake kudaathu!! The ...",Positive,Tamil,appedilaam nadekaathu nadake kudaathu the bull...
3,Looks like d Mixture of Kaala+Kabali..... ...,Positive,Tamil,looks like d mixture of kaalakabali sure antho...
4,Nfg greatest hits cd cracked,Negative,English,nfg greatest hits cd cracked

In [3]:
print(df.shape)

(30978, 4)

In [4]:
df["sentiment"].value_counts()

sentiment
Positive    18690
Negative    12288
Name: count, dtype: int64

In [5]:
df["label"] = df["sentiment"].map({
    "Negative": 0,
    "Positive": 1
})

In [6]:
df[["sentiment", "label"]].head()

  sentiment  label
0  Positive      1
1  Positive      1
2  Positive      1
3  Positive      1
4  Negative      0

In [7]:
df["label"].value_counts()

label
1    18690
0    12288
Name: count, dtype: int64

In [8]:
X = df["cleaned_text"]

y = df["label"]

In [9]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [10]:
print("Train:", X_train.shape)
print("Test :", X_test.shape)

Train: (24782,)
Test : (6196,)

In [11]:
tfidf = TfidfVectorizer(
    max_features=10000,
    ngram_range=(1,2)
)

In [12]:
X_train_tfidf = tfidf.fit_transform(X_train)

X_test_tfidf = tfidf.transform(X_test)

In [13]:
print(X_train_tfidf.shape)

print(X_test_tfidf.shape)

(24782, 10000)
(6196, 10000)

In [14]:
print(
    "Vocabulary Size:",
    len(tfidf.vocabulary_)
)

Vocabulary Size: 10000

In [15]:
feature_names = tfidf.get_feature_names_out()

print(feature_names[:50])

['aa' 'aaa' 'aaaa' 'aaaaaa' 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaasaaaa'
 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaasaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaasaaaa'
 'aaah' 'aachu' 'aadukalam' 'aaga' 'aagala' 'aagudhu' 'aagum' 'aaguthu'
 'aah' 'aairuku' 'aairuku pangalingala' 'aalu' 'aamai' 'aana' 'aanalum'
 'aatatha' 'ab' 'able' 'able to' 'about' 'about an' 'about it' 'about me'
 'about my' 'about now' 'about that' 'about the' 'about this' 'about to'
 'about what' 'about you' 'about your' 'above' 'absolutely' 'abt' 'abuse'
 'ac' 'accept' 'access' 'accident' 'according' 'according to' 'account'
 'ache']

In [16]:
import os

os.makedirs("../models", exist_ok=True)

In [17]:
import joblib

joblib.dump(
    tfidf,
    "../models/tfidf_vectorizer.pkl"
)

print("Vectorizer Saved")

Vectorizer Saved

FEATURE ENGINEERING SUMMARY

Dataset Loaded Successfully

Labels Encoded:
Positive → 1
Negative → 0

Train-Test Split:
80% Training
20% Testing

Feature Extraction:
TF-IDF Vectorization

Parameters:
max_features = 10000
ngram_range = (1,2)

Vectorizer Saved:
models/tfidf_vectorizer.pkl